### ISSUE TITLE
添加 API 文档

### ISSUE THREAD

**Issue by jaxvanyang** [WebChatting/chatting#38]
- [x] 列出所有的 API
- [ ] 列出需要转发的 API 前缀
- [ ] 提供 Nginx 代理模板

#13

**Comment by Crazyokd** [comment]
API 还在找自动导出方案，API成熟后，计划使用github-pages自动更新部署

**Comment by jaxvanyang** [comment]
> API 还在找自动导出方案，API成熟后，计划使用github-pages自动更新部署

语义化版本也应该和 API 状态一致。

**Comment by Crazyokd** [comment]
nginx代理模板麻烦你在前端仓库给出吧@jaxvanyang

**Comment by Crazyokd** [comment]
转发API前缀就现在cd跑的这个就行，以后有变动再改，前端也使用docker-compose，chatting-vue + nginx，相应的代码麻烦支持一下@jaxvanyang
