### ISSUE TITLE
建议分支名按 <type>/<title> 格式命名

### ISSUE THREAD

**Issue by jaxvanyang** [WebChatting/chatting#43]
例如 feat/interface。

CD 可以设置在特定的分支上触发：

![image](https://user-images.githubusercontent.com/25650612/224368721-edc8b15b-0c53-4ab2-a479-95228d0a2eb7.png)

这样让 CD 尽量跑最新的版本，虽然生产中应该只部署主分支。这是没有完善的测试 CI 的 workaround。

**Comment by Crazyokd** [comment]
以前没有这个习惯，学到了
